teams/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import Home, TeamsListView, ScoresListView, PlayerDetailsView, TeamDetailsView, AddTeamView, \
    AddPlayerView, DeleteEvent, errorbooking, Consultations, DeleteConsultations, Contact, News, delete_score, delete_player

urlpatterns = [
    path('', views.Home, name='Home'),
    path('home', views.Home, name='Home'),
    path('bookingandpurchaseshistory', views.bookingAndPurchasesHistoryFunc, name='BookingAndPurchasesHistory'),
    path('teamformation', views.TeamFormation, name='TeamFormation'),

    path('adminpage', views.AdminPage, name='AdminPage'),

    url('login', views.Login, name='Login'),
    url('register', views.Register, name='Register'),

    path('adminpage/addupcomingmatches/', views.addupcomingmatches, name='add'),
    path('adminpage/addupcomingmatches/addrecordupcomingmatches/', views.addrecordupcomingmatches, name='addrecord'),
    path('adminpage/deleteupcomingmatches/<int:id>', views.deleteupcomingmatches, name='delete'),
    path('adminpage/updateupcomingmatches/<int:id>', views.updateupcomingmatches, name='update'),
    path('adminpage/updateupcomingmatches/updaterecordupcomingmatches/<int:id>', views.updaterecordupcomingmatches, name='updaterecord'),
    
    path('adminpage/addnewsletter/', views.addnewsletter, name='add'),
    path('adminpage/addnewsletter/addrecordnewsletter/', views.addrecordnewsletter, name='addrecord'),
    path('adminpage/deletenewsletter/<int:id>', views.deletenewsletter, name='delete'),
    path('adminpage/updatenewsletter/<int:id>', views.updatenewsletter, name='update'),
    path('adminpage/updatenewsletter/updaterecordnewsletter/<int:id>', views.updaterecordnewsletter, name='updaterecord'),

    path('adminpage/addbookingandpurchaseshistory/', views.addbookingandpurchaseshistory, name='add'),
    path('adminpage/addbookingandpurchaseshistory/addrecordbookingandpurchaseshistory/', views.addrecordbookingandpurchaseshistory, name='addrecord'),
    path('adminpage/deletebookingandpurchaseshistory/<int:id>', views.deletebookingandpurchaseshistory, name='delete'),
    path('adminpage/updatebookingandpurchaseshistory/<int:id>', views.updatebookingandpurchaseshistory, name='update'),
    path('adminpage/updatebookingandpurchaseshistory/updaterecordbookingandpurchaseshistory/<int:id>', views.updaterecordbookingandpurchaseshistory, name='updaterecord'),

    path('adminpage/updateteamformation/<int:id>', views.updateteamformation, name='update'),
    path('adminpage/updateteamformation/updaterecordteamformation/<int:id>', views.updaterecordteamformation, name='updaterecord'),   


    url(r'^teams/$', TeamsListView.as_view(), name="teams-list-view"),
    url(r'^scores/$', ScoresListView.as_view(), name="scores-list-view"),

    url(r'^player/(?P<slug>[-\w\x20]+)/$', PlayerDetailsView.as_view(), name="player-details-view"),
    url(r'^team/(?P<slug>[-\w\x20]+)/$', TeamDetailsView.as_view(), name="team-details-view"),

    url(r'^add_team/$', AddTeamView.as_view(), name="add-team-view"),
    url(r'^add_player/$', AddPlayerView.as_view(), name="add-player-view"),
    url(r'^delete_matches/$', DeleteEvent, name="delete-matches-view"),
    url(r'^consultation/$', Consultations.as_view(), name="consultation"),
    url(r'^delete_consultation/$', DeleteConsultations, name="delete-consultation-view"),
    url(r'^contact/$', Contact, name="contact-view"),
    url(r'^latest_news/$', News, name="news-view"),
    path(r'^delete_score/<int:id>/$', delete_score, name='delete-score'),
    path(r'^delete_player/<int:id>/$', delete_player, name='delete-player'),


]

teams/models.py
from django.db import models

import datetime
# Create your models here.
from django.db.models import DO_NOTHING
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
alphanumeric = RegexValidator(r'^([a-zA-Z]+\s)*[a-zA-Z]+$', 'Only characters are allowed.')



class Team(models.Model):
    name = models.CharField(max_length=256, unique=True)
    details = models.TextField()

    # Display Team name instead of Object when calling a Team instance from database
    def __str__(self):
        return self.name


class Player(models.Model):
    name = models.CharField(max_length=256, validators=[alphanumeric])
    number = models.PositiveIntegerField()
    age = models.PositiveIntegerField()
    position_in_field = models.CharField(max_length=256,
                                         choices=(('1', 'GK'), ('2', 'RB'), ('3', 'RM'), ('4', 'ST')))
    is_captain = models.BooleanField(default=False)
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)

    # Display playerName - clubName instead of Object
    def __str__(self):
        return '{} - {}'.format(self.name, self.team)


class GameScore(models.Model):
    first_team_relation = models.ForeignKey(Team, related_name='first_team', null=True, on_delete=DO_NOTHING)
    second_team_relation = models.ForeignKey(Team, related_name='second_team', null=True, on_delete=DO_NOTHING)
    first_team_score = models.PositiveIntegerField(default=0)
    second_team_score = models.PositiveIntegerField(default=0)
    game_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {} - {} {}'.format(self.first_team_relation.name, self.first_team_relation.name, self.second_team_score, self.second_team)
    
    def clean(self):
        if self.first_team_relation == self.second_team_relation:
            raise ValidationError('First and Second Team should be different.')
    
class Consultation(models.Model):
    name_1 = models.CharField(max_length=256, validators=[alphanumeric])
    number = models.PositiveIntegerField()
    date = models.DateField(default=datetime.date.today)
    time = models.CharField(max_length=256,
                                         choices=(('1', '1PM - 2PM'), ('2', '2PM - 3PM'), ('3', '3PM - 4PM'), ('4', '4PM - 5PM')), default=None, 
                                         )
    coach_name = models.CharField(max_length= 256, 
                                  choices=(('1', 'Youssef El Sayed'), ('2', 'Karim Nasreddine'), ('3', 'Jad Jawad'), ('4', 'Yasmina Mehshi'), ('5', 'Salwa Fidawi')), default=None, 
                                  )

    def __str__(self):
        return '{} - {}'.format(self.name_1, self.number)

    
class Teams(models.Model):
  time = models.CharField(max_length=255)
  homeTeam = models.CharField(max_length=255)
  awayTeam = models.CharField(max_length=255)
  
  class Meta:
      verbose_name_plural = "Upcoming Games"

class BookingAndPurchasesHistoryModel(models.Model):
  time = models.CharField(max_length=255)
  description = models.CharField(max_length=255)
  
  class Meta:
      verbose_name_plural = "Booking and Purchases History"


# SP: Starting Player / NS: Not Selected
class TeamFormationModel(models.Model):
  # STARTING PLAYERS
  GK_SP = models.CharField(max_length=255)        # Goalkeeper
  DF_SP_L = models.CharField(max_length=255)      # Defender
  DF_SP_LM = models.CharField(max_length=255)     # Defender
  DF_SP_RM = models.CharField(max_length=255)     # Defender
  DF_SP_R = models.CharField(max_length=255)      # Defender
  MF_SP_L = models.CharField(max_length=255)      # Midfielder
  MF_SP_LM = models.CharField(max_length=255)     # Midfielder
  MF_SP_RM = models.CharField(max_length=255)     # Midfielder
  MF_SP_R = models.CharField(max_length=255)      # Midfielder
  FW_SP_LW = models.CharField(max_length=255)     # Left Wing
  FW_SP_RW = models.CharField(max_length=255)     # Right Wing
  # PLAYERS ON BENCH / NOT SELECTED
  GK_NS = models.CharField(max_length=255)        # Goalkeeper
  DF_NS_1 = models.CharField(max_length=255)      # Defender
  DF_NS_2 = models.CharField(max_length=255)      # Defender
  MF_NS_1 = models.CharField(max_length=255)      # Midfielder
  MF_NS_2 = models.CharField(max_length=255)      # Midfielder
  FW_NS_LW = models.CharField(max_length=255)     # Left Wing
  FW_NS_RW = models.CharField(max_length=255)     # Right Wing

  class Meta:
      verbose_name_plural = "Team Formation"


class Newsletter(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()

    class Meta:
        verbose_name_plural = "Newsletter"

class Users(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    admin = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Users"

teams/templates/add_consultation.html
{% load crispy_forms_tags %}

<form action="/consultation/" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>

<br>

<div>
    <a href={% url 'delete-consultation-view' %}>Delete Latest Consultation</a>
    </div>
    <br>

teams/templates/adminaddbookingandpurchaseshistory.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Booking and Purchases History</title>
    <style>
      {% include "static/adminsecondarypages.css" %}
    </style>
  </head>
  <body>
    <h1>Add Booking and Purchases History</h1>

    <form action="addrecordbookingandpurchaseshistory/" method="post">
      {% csrf_token %}
      Time:
      <br />
      <input name="time" />
      <br /><br />
      Description:
      <br />
      <input name="description" />
      <br /><br />
      <input type="submit" value="Submit" />
    </form>
  </body>
</html>

teams/templates/adminaddupcomingmatches.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Upcoming Matches</title>
    <style>
      {% include "static/adminsecondarypages.css" %}
    </style>
  </head>
  <body>
    <h1>Add Match</h1>

    <form action="addrecordupcomingmatches/" method="post">
      {% csrf_token %} Time:<br />
      <input name="time" />
      <br /><br />
      Home Team:<br />
      <input name="homeTeam" />
      <br /><br />
      Away Team:<br />
      <input name="awayTeam" />
      <br /><br />
      <input type="submit" value="Submit" />
    </form>
  </body>
</html>

teams/templates/adminpage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Page</title>
    <link rel="stylesheet" href="../static/css/nicepage.css" media="screen" />
    <link rel="stylesheet" href="../static/css/FC-Eagles.css" media="screen" />
    <script
      class="u-script"
      type="text/javascript"
      src="../static/jquery.js"
      defer=""
    ></script>
    <script
      class="u-script"
      type="text/javascript"
      src="../static/nicepage.js"
      defer=""
    ></script>
    <style>
      {% include "static/adminpage.css" %}
    </style>
    <link rel="icon" href="../static/images/EaglesFavicon.png" />
    <link
      id="u-theme-google-font"
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i"
    />
    <link
      id="u-page-google-font"
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700"
    />
  </head>
  <body style="display: flex; flex-direction: column; align-items: center">
    <h4>
      <a href="/" style="color: white; padding: 1em; text-decoration: underline"
        >Back to Homepage</a
      >
    </h4>
    <h1>Upcoming Matches</h1>

    <table class="customTable" border="1">
      <tr>
        <th>ID</th>
        <th>Time</th>
        <th>Home Team</th>
        <th>Away Team</th>
      </tr>
      {% for x in myteams %}
      <tr>
        <td>
          <a href="adminpage/updateupcomingmatches/{{ x.id }}">update</a>
        </td>
        <td>{{ x.time }}</td>
        <td>{{ x.homeTeam }}</td>
        <td>{{ x.awayTeam }}</td>
        <td><a href="adminpage/deleteupcomingmatches/{{ x.id }}">delete</a></td>
      </tr>

      {% endfor %}
    </table>

    <p>
      <a href="adminpage/addupcomingmatches/">Add Match</a>
    </p>

    <h1>Newsletters</h1>

    <table class="customTable" border="1">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email Address</th>
      </tr>
      {% for x in mynewsletters %}
      <tr>
        <td><a href="adminpage/updatenewsletter/{{ x.id }}">update</a></td>
        <td>{{ x.name }}</td>
        <td>{{ x.email }}</td>
        <td><a href="adminpage/deletenewsletter/{{ x.id }}">delete</a></td>
      </tr>

      {% endfor %}
    </table>

    <p>
      <a href="adminpage/addnewsletter/">Add Newsletter</a>
    </p>

    <h1>Booking and Purchases History</h1>

    <table class="customTable" border="1">
      <tr>
        <th>ID</th>
        <th>Time</th>
        <th>Description</th>
      </tr>
      {% for x in mybookingandpurchaseshistory %}
      <tr>
        <td>
          <a href="adminpage/updatebookingandpurchaseshistory/{{ x.id }}"
            >update</a
          >
        </td>
        <td>{{ x.time }}</td>
        <td>{{ x.description }}</td>
        <td>
          <a href="adminpage/deletebookingandpurchaseshistory/{{ x.id }}"
            >delete</a
          >
        </td>
      </tr>

      {% endfor %}
    </table>

    <p>
      <a href="adminpage/addbookingandpurchaseshistory/">Add Entry</a>
    </p>

    <h1>Team Formation</h1>

    <table class="customTable" id="teamformationtable" border="1">
      <tr>
        <th style="border: none !important"></th>
        <th>GK SP:</th>
        <th>DF SP L:</th>
        <th>DF SP LM:</th>
        <th>DF SP R:</th>
        <th>DF SP RM:</th>
        <th>MF SP L:</th>
        <th>MF SP LM:</th>
        <th>MF SP R:</th>
        <th>MF SP RM:</th>
        <th>FW SP LW:</th>
        <th>FW SP RW:</th>
        <th>GK NS:</th>
        <th>DF NS 1:</th>
        <th>DF NS 2:</th>
        <th>MF NS 1:</th>
        <th>MF NS 2:</th>
        <th>FW NS LW:</th>
        <th>FW NS RW:</th>
      </tr>
      {% for x in myteamformation %}
      <tr>
        <td>
          <a href="adminpage/updateteamformation/{{ x.id }}"> update </a>
        </td>
        <td>{{ x.GK_SP }}</td>
        <td>{{ x.DF_SP_L }}</td>
        <td>{{ x.DF_SP_LM }}</td>
        <td>{{ x.DF_SP_R }}</td>
        <td>{{ x.DF_SP_RM }}</td>
        <td>{{ x.MF_SP_L }}</td>
        <td>{{ x.MF_SP_LM }}</td>
        <td>{{ x.MF_SP_R }}</td>
        <td>{{ x.MF_SP_RM }}</td>
        <td>{{ x.FW_SP_LW }}</td>
        <td>{{ x.FW_SP_RW }}</td>
        <td>{{ x.GK_NS }}</td>
        <td>{{ x.DF_NS_1 }}</td>
        <td>{{ x.DF_NS_2 }}</td>
        <td>{{ x.MF_NS_1 }}</td>
        <td>{{ x.MF_NS_2 }}</td>
        <td>{{ x.FW_NS_LW }}</td>
        <td>{{ x.FW_NS_RW }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

teams/templates/adminupdateupcomingmatches.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Update Upcoming Matches</title>
    <style>
      {% include "static/adminsecondarypages.css" %}
    </style>
  </head>
  <body>
    <h1>Update Match</h1>

    <form action="updaterecordupcomingmatches/{{ myteam.id }}" method="post">
      {% csrf_token %} Time:<br />
      <input name="time" value="{{ myteam.time }}" />
      <br /><br />
      Home Team:<br />
      <input name="homeTeam" value="{{ myteam.homeTeam }}" />
      <br /><br />
      Away Team:<br />
      <input name="awayTeam" value="{{ myteam.awayTeam }}" />
      <br /><br />
      <input type="submit" value="Submit" />
    </form>
  </body>
</html>

teams/templates/consultation.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Consultation Results {% endblock %}

{% block content %}
    <div align="center">
        <img class="icon-width" src="{% static 'images/consultation.png' %}" alt="">
    </div>
    <div align="center">
        {% include 'add_consultation.html' %}
    </div>
    {% for c in consultation %}
        <div align="center">

            <h2> {{ c.name_1 }} reserved with {{ c.get_coach_name_display }} on {{ c.date }} at {{ c.get_time_display }}</h2>
        </div>
    {% endfor %}

{% endblock %}

teams/templates/contact.html
<!DOCTYPE html>
<body>
  <html lang="en">
    {% extends 'base.html' %} {% load static %}

    <head>
      {% load static %}
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Contact Us</title>
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Slab&display=swap"
        rel="stylesheet"
      />
      <link rel="stylesheet" href="{% static 'static/adminpage.css' %}" />
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous"
      />
    </head>
    {% block content %}

    <body>
      <div class="container">
        <header>
          <h1 style="color: white; font-family: Lalezar">Contact Us</h1>
          <p>Contact us for any queries you may have!</p>
        </header>
        <div class="content">
          <div class="content-form">
            <section style="height: fit-content">
              <i class="fa fa-map-marker fa-2x" aria-hidden="true"></i>
              <h2>Address</h2>
              <p>
                Building XYZ <br />
                Street 123 <br />
                City ABC
              </p>
            </section>

            <section style="height: fit-content">
              <i class="fa fa-phone fa-2x" aria-hidden="true"></i>
              <h2>Phone</h2>
              <p>001-234-5678</p>
            </section>

            <section style="height: fit-content">
              <i class="fa fa-envelope fa-2x" aria-hidden="true"></i>
              <h2>E-mail</h2>
              <p>eaglesfc@gmail.com</p>
            </section>
          </div>
        </div>
      </div>
    </body>
    {% endblock %}
  </html>
</body>

teams/templates/error_booking.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Booking Results {% endblock %}

{% block content %}
    <div align="center">
        <img class="icon-width" src="{% static 'images/error.png' %}" alt="">
    </div>
    <h2> Field Is Already reserved at that time. </h2>
    <h2> Please choose a different slot. Thank you </h2>
    


{% endblock %}

teams/templates/team_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <img class="icon-width" src="{% static 'images/ic_team.png' %}" alt="">

    <h2>{{ team.name }}</h2>
    <p>{{ team.details }}</p>

    {% for player in team.player_set.all %}
        <a href="/player/{{ player.name }}">
            <h3>{{ player.name }}</h3>
        </a>
    {% endfor %}
    
        <table style= "margin-left: auto; margin-right: auto; margin: 25px 0 font-size: 0.9em font-family: sans-serif min-width: 400px box-shadow: 0 0 20px rgba(0, 0, 0, 0.15) background-color: #009879; color: #ffffff; text-align: left;"
      border="thin">

        {% for player in team.player_set.all %}
          <tr style= "background-color: #60c1ad">
          <td>{{ player.id }}</td>
          <td>{{ player.name }}</td>
          <td>{{ player.team.name }}</td>
          <td><a href={% url 'delete-player' id=player.id %}>delete</a></td>
          </tr>
        {% endfor %}
        </table>


{% endblock %}

teams/templates/teams_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} List of Teams {% endblock %}

{% block content %}
<div style="display: flex; flex-direction: column; align-items: center">
    <img class="icon-width" src="{% static 'images/ic_teams_list.png' %}" alt="">

    {% for team in teams %}
        <a href="/team/{{ team.name }}">
            <h2> {{ team.name }} </h2>
        </a>
        <p> {{ team.details }} </p>
    {% endfor %}
</div>

{% endblock %}